### ISSUE TITLE
handle DAI and MKR being mistakenly sent to DaiBackstopSyndicate or Bidder contract (tip jar?)

### ISSUE THREAD

**Issue by thegostep** [backstop-syndicate/dai-backstop-syndicate#21]

**Comment by GriffGreen** [comment]
Just give Sam and some other white hats some escape hatch logic... a couple people can call the escape hatch (White hats Alice, Bob and Carol) which then send the money to a multisig that a couple other white hats are on (David, Eva, Fred and Grace) are on and then let them manually do the refund, i don't imagine it would ever be more than 3 people making this mistake. 

an old version showing the logic is here: https://github.com/Giveth/common-contract-deps/blob/master/contracts/Escapable.sol
